### ISSUE TITLE
Tinkering with .net core

### ISSUE THREAD

**Issue by marbletravis** [Centeva/TypeScripter#18]
When I point it to a dll in .net core, it doesn't seem to see any of the controllers.

ApiController is now just Controller in .net core, so I have adjusted the config as such.

There is a good chance this is just because its .net core, but I started debugging and the GetTypes() in the following function throws an exception

`private static IEnumerable<Type> TryGetApiControllerTypes(Assembly a)
		{
		    try
		    {
                var types = a.GetTypes();
		        return types;
		    }
			catch { return Enumerable.Empty<Type>(); }
		}`

The exception is "Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information."

Am I headed in the right direction, do you think its a .net core issue or am I doing something else wrong?

**Comment by darrelbrown** [comment]
I don't have enough experience with .net core to be certain about the source of the problem.  I'd look at the LoaderExceptions for clues.  I wouldn't give up yet because, according to MSDN that reflection method should be supported.  

https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.gettypes?view=netcore-2.0

**Comment by marbletravis** [comment]
@darrelbrown It looks like a build in dotnetcore is not portable... dotnetcore only creates a portable build when you do `dotnet publish` 

see answer to 
https://stackoverflow.com/questions/43837638/how-to-get-net-core-projects-to-copy-nuget-references-to-build-output

I could set the property as shown in example, or is there another way to work around this?

**Comment by marbletravis** [comment]
typescripter fully supports .netcore.
